default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: abs_next_gen_be_development

test:
  <<: *default
  database: abs_next_gen_be_test

production:
  <<: *default
  database: abs_next_gen_be_production
  username: abs_next_gen_be
  password: <%= ENV['ABS_NEXT_GEN_BE_DATABASE_PASSWORD'] %>
